// generated by claude opus 4.7
package openai

import (
	"context"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/joho/godotenv"
)

func TestMain(m *testing.M) {
	_ = godotenv.Load("../../.env")
	os.Exit(m.Run())
}

func TestNew_Singleton(t *testing.T) {
	if os.Getenv("OPENAI_API_KEY") == "" {
		t.Skip("OPENAI_API_KEY not set")
	}

	c1, err := New()
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	c2, err := New()
	if err != nil {
		t.Fatalf("New (second call): %v", err)
	}
	if c1 != c2 {
		t.Fatalf("singleton violated: %p != %p", c1, c2)
	}
	if c1.http == nil {
		t.Fatal("http client not initialized")
	}
	if c1.APIKey == "" {
		t.Fatal("APIKey empty")
	}
	if c1.Dim <= 0 {
		t.Fatalf("invalid Dim: %d", c1.Dim)
	}
}

func TestEmbed_EmptyInput(t *testing.T) {
	c := &Client{APIKey: "test", Dim: 128, http: &http.Client{Timeout: time.Second}}

	cases := []string{"", "   ", "\t\n"}
	for _, in := range cases {
		if _, err := c.Embed(context.Background(), in); err == nil {
			t.Fatalf("expected error for input %q", in)
		}
	}
}

func TestEmbed_Network(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in -short mode")
	}
	if os.Getenv("OPENAI_API_KEY") == "" {
		t.Skip("OPENAI_API_KEY not set")
	}

	c, err := New()
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	vec, err := c.Embed(ctx, "hello world")
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}
	if len(vec) != c.Dim {
		t.Fatalf("dim mismatch: want %d got %d", c.Dim, len(vec))
	}
}
