// generated by claude opus 4.7
package openai

import (
	"context"
	"net/http"
	"os"
	"testing"
	"time"
)

func TestNew_KeyPriority(t *testing.T) {
	t.Setenv("OPENAI_API_KEY", "from-env")

	c, err := New("injected")
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if c.APIKey != "injected" {
		t.Fatalf("injected key should win over env, got %q", c.APIKey)
	}
	if c.http == nil {
		t.Fatal("http client not initialized")
	}

	c, err = New("")
	if err != nil {
		t.Fatalf("New(empty): %v", err)
	}
	if c.APIKey != "from-env" {
		t.Fatalf("empty key should fall back to env, got %q", c.APIKey)
	}
	if c.Dim <= 0 {
		t.Fatalf("invalid Dim: %d", c.Dim)
	}
}

func TestEmbed_EmptyInput(t *testing.T) {
	c := &Client{APIKey: "test", Dim: 128, http: &http.Client{Timeout: time.Second}}

	cases := []string{"", "   ", "\t\n"}
	for _, in := range cases {
		if _, err := c.Embed(context.Background(), in); err == nil {
			t.Fatalf("expected error for input %q", in)
		}
	}
}

func TestEmbed_Network(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in -short mode")
	}
	if os.Getenv("OPENAI_API_KEY") == "" {
		t.Skip("OPENAI_API_KEY not set")
	}

	c, err := New("")
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	vec, err := c.Embed(ctx, "hello world")
	if err != nil {
		t.Fatalf("Embed: %v", err)
	}
	if len(vec) != c.Dim {
		t.Fatalf("dim mismatch: want %d got %d", c.Dim, len(vec))
	}
}
