// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestEntry_Value(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	sess.Exec("SET k1 hello")

	entry, ok := sess.Get("k1")
	if !ok {
		t.Fatal("Get(k1) returned false")
	}
	if got := entry.Value(); got != "hello" {
		t.Errorf("Value() = %q, want hello", got)
	}
}

func TestSession_Set(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	tests := []struct {
		name    string
		key     string
		value   string
		flag    store.SetFlag
		wantErr bool
	}{
		{"simple", "k1", "v1", store.SetDefault, false},
		{"json", "k2", `{"a":1}`, store.SetDefault, false},
		{"int", "k3", "42", store.SetDefault, false},
		{"float", "k4", "3.14", store.SetDefault, false},
		{"bool", "k5", "true", store.SetDefault, false},
		{"NX on new", "k6", "v6", store.SetNX, false},
		{"NX on existing", "k1", "v1b", store.SetNX, true},
		{"XX on existing", "k1", "v1b", store.SetXX, false},
		{"XX on new", "k7", "v7", store.SetXX, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := sess.Set(tt.key, tt.value, tt.flag, nil)
			if (err != nil) != tt.wantErr {
				t.Errorf("Set(%q, %q, %v) error = %v, wantErr %v", tt.key, tt.value, tt.flag, err, tt.wantErr)
			}
		})
	}
}

func TestValueType_String(t *testing.T) {
	tests := []struct {
		name string
		vt   store.ValueType
		want string
	}{
		{"string", store.TypeString, "string"},
		{"int", store.TypeInt, "int"},
		{"float", store.TypeFloat, "float"},
		{"bool", store.TypeBool, "bool"},
		{"json", store.TypeJSON, "json"},
		{"date", store.TypeDate, "date"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.vt.String(); got != tt.want {
				t.Errorf("String() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestSession_SetVector(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// SetVector may fail if no OPENAI_API_KEY — that's expected
	err = sess.SetVector(nil, "vk1", "hello world", store.SetDefault, nil)
	if err != nil {
		t.Logf("SetVector failed (expected without API key): %v", err)
	}
}
