// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"os"
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestStore_New(t *testing.T) {
	t.Run("default path", func(t *testing.T) {
		s, err := store.New(tempDir(t))
		if err != nil {
			t.Fatalf("store.New: %v", err)
		}
		if s == nil {
			t.Fatal("store.New returned nil")
		}
		s.Close()
	})

	t.Run("too many api keys", func(t *testing.T) {
		_, err := store.New(tempDir(t), "k1", "k2")
		if err == nil {
			t.Error(`store.New(dir, "k1", "k2") should return error`)
		}
	})

	t.Run("not a directory", func(t *testing.T) {
		dir := tempDir(t)
		f, err := os.CreateTemp(dir, "file-*")
		if err != nil {
			t.Fatalf("CreateTemp: %v", err)
		}
		f.Close()
		_, err = store.New(f.Name())
		if err == nil {
			t.Error("store.New(file) should return error")
		}
	})
}

func TestStore_Close(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	if err := s.Close(); err != nil {
		t.Errorf("Close: %v", err)
	}
}

func TestStore_Session(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	if sess == nil {
		t.Fatal("Session returned nil")
	}
}

func TestSession_Select(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	tests := []struct {
		name    string
		index   int
		wantErr bool
	}{
		{"valid 0", 0, false},
		{"valid 15", 15, false},
		{"negative", -1, true},
		{"too large", 16, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := sess.Select(tt.index)
			if (err != nil) != tt.wantErr {
				t.Errorf("Select(%d) error = %v, wantErr %v", tt.index, err, tt.wantErr)
			}
		})
	}
}

func TestSession_Current(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	if got := sess.Current(); got != 0 {
		t.Errorf("Current() = %d, want 0", got)
	}
	sess.Select(5)
	if got := sess.Current(); got != 5 {
		t.Errorf("Current() = %d, want 5", got)
	}
}

func TestSession_DB(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	db := sess.DB()
	if db == nil {
		t.Fatal("DB() returned nil")
	}
}
