name: go-test-and-coverage

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Go tests with coverage
        run: go test ./... -count=1 -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/develop'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          fail_ci_if_error: true
          verbose: true
